spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: qwerrewq12!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      use-new-id-generator-mappings: true
    properties:
      hibernate.hbm2ddl.auto: create
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: Asia/Seoul

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE